#!/usr/bin/env python3
"""
bootstrap_supersonic.py
Writes all support files for SonicBuilder:
- deploy_github.py  (one-and-done GitHub deployer)
- replit_to_github.sh (Replit → GitHub wrapper)
- Makefile (nice shortcuts)
- GitHub Actions (CI + Release)
- vendor fetchers: tools/get_pdfjs.sh, tools/get_jszip.sh
- .env.example

Usage:
  python3 bootstrap_supersonic.py
Then:
  chmod +x replit_to_github.sh
  # (optional) gh auth login
  export GITHUB_OWNER=YOUR_USER_OR_ORG
  export GITHUB_REPO=SonicBuilder
  export GIT_AUTHOR_NAME="Christopher Elgin"
  export GIT_AUTHOR_EMAIL="you@example.com"
  ./replit_to_github.sh
"""

import os, stat
from pathlib import Path

ROOT = Path(__file__).resolve().parent

def write(path: Path, content: str, make_exe: bool=False):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if make_exe:
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"→ Wrote {path}")

# ---------------- deploy_github.py ----------------
DEPLOY_GITHUB = r"""#!/usr/bin/env python3
import json, os, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

OWNER   = os.getenv("GITHUB_OWNER",   "your-username-or-org")
REPO    = os.getenv("GITHUB_REPO",    "SonicBuilder")
TOKEN   = os.getenv("GITHUB_TOKEN",   "")
AUTHOR  = os.getenv("GIT_AUTHOR_NAME","Supersonic Bot")
EMAIL   = os.getenv("GIT_AUTHOR_EMAIL","bot@example.com")
BRANCH  = os.getenv("GIT_DEFAULT_BRANCH","main")
MSG     = os.getenv("COMMIT_MSG","Supersonic: initial import")
PUSH_FORCE   = os.getenv("PUSH_FORCE","0") == "1"
ADD_LFS      = os.getenv("ADD_LFS","1") == "1"
ADD_WORKFLOW = os.getenv("ADD_WORKFLOW","1") == "1"
VISIBILITY   = os.getenv("VISIBILITY","private").lower().strip()

REMOTE_URL = f"https://github.com/{OWNER}/{REPO}.git"

LFS_PATTERNS = [
    "*.zip","*.7z","*.rar",
    "assets/audio/*.wav","assets/audio/*.mp3",
    "static/vendor/**",
    "docs/**/*.pdf","assets/**/*.pdf",
    "*.png","*.jpg","*.jpeg",
]

GITIGNORE = """__pycache__/
*.pyc
.env
.env.*
.venv/
venv/
dist/
build/
node_modules/
*.log
.DS_Store
.replit
replit.nix
.idea/
.vscode/
.cache/
*.cache/
pip-wheel-metadata/
*.zip
*.7z
*.tar
*.tar.gz
*.egg-info/
tmp/
local/
"""

WORKFLOW_YML = """name: Supersonic CI
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install basics
        run: |
          python -m pip install --upgrade pip
          pip install flask
      - name: Smoke test app import
        run: |
          python - <<'PY'
          try:
              import app
              print("✅ app.py import OK")
          except Exception as e:
              print("❌ app.py import failed:", e)
              raise
          PY
"""

def run(cmd, check=True, capture=False):
    if capture:
        return subprocess.run(cmd, check=check, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True).stdout
    subprocess.run(cmd, check=check)

def have_cmd(bin_name: str) -> bool:
    return shutil.which(bin_name) is not None

def git(*args, check=True, capture=False):
    return run(["git", *args], check=check, capture=capture)

def ensure_git_repo():
    if not (ROOT / ".git").exists():
        print("→ Initializing git repo")
        git("init", "-b", BRANCH)
    else:
        try:
            git("rev-parse", "--verify", BRANCH)
        except subprocess.CalledProcessError:
            git("checkout", "-b", BRANCH)
        else:
            git("checkout", BRANCH)
    print("→ Setting author")
    git("config", "user.name", AUTHOR)
    git("config", "user.email", EMAIL)

def ensure_gitignore():
    gi = ROOT / ".gitignore"
    if not gi.exists():
        gi.write_text(GITIGNORE)
        print("→ Wrote .gitignore")

def ensure_lfs():
    if not ADD_LFS:
        print("→ Skipping Git LFS setup (ADD_LFS=0)")
        return
    if not have_cmd("git"):
        raise SystemExit("git not found in PATH")
    print("→ Ensuring Git LFS")
    if not have_cmd("git-lfs"):
        print("  ! git-lfs not found; skipping LFS (install it to use).")
        return
    run(["git", "lfs", "install"])
    gattr = ROOT / ".gitattributes"
    existing = gattr.read_text() if gattr.exists() else ""
    lines = existing.splitlines() if existing else []
    changed = False
    for pat in LFS_PATTERNS:
        rule = f"{pat} filter=lfs diff=lfs merge=lfs -text"
        if rule not in lines:
            lines.append(rule)
            changed = True
    if changed:
        gattr.write_text("\n".join(lines) + "\n")
        print(f"→ Updated .gitattributes with {len(LFS_PATTERNS)} LFS patterns")
    else:
        print("→ .gitattributes already contains LFS patterns")

def ensure_workflow():
    if not ADD_WORKFLOW:
        print("→ Skipping workflow (ADD_WORKFLOW=0)")
        return
    wf_dir = ROOT / ".github" / "workflows"
    wf_dir.mkdir(parents=True, exist_ok=True)
    wf = wf_dir / "supersonic-ci.yml"
    if not wf.exists():
        wf.write_text(WORKFLOW_YML)
        print("→ Added .github/workflows/supersonic-ci.yml")

def repo_exists_remote() -> bool:
    if have_cmd("gh"):
        try:
            run(["gh", "repo", "view", f"{OWNER}/{REPO}"], check=True, capture=True)
            return True
        except subprocess.CalledProcessError:
            return False
    if TOKEN:
        import urllib.request, urllib.error
        req = urllib.request.Request(
            f"https://api.github.com/repos/{OWNER}/{REPO}",
            headers={"Authorization": f"Bearer {TOKEN}",
                     "Accept":"application/vnd.github+json",
                     "X-GitHub-Api-Version":"2022-11-28"}
        )
        try:
            with urllib.request.urlopen(req) as resp:
                return resp.status == 200
        except urllib.error.HTTPError as e:
            return False
    return True

def create_repo_if_needed():
    if repo_exists_remote():
        print(f"→ Remote repo {OWNER}/{REPO} already exists")
        return
    print(f"→ Creating repo {OWNER}/{REPO} ({VISIBILITY})")
    if have_cmd("gh"):
        vis_flag = "--private" if VISIBILITY == "private" else "--public"
        run(["gh", "repo", "create", f"{OWNER}/{REPO}", vis_flag, "--confirm"])
        return
    if not TOKEN:
        raise SystemExit("No gh and no GITHUB_TOKEN set; cannot create repo automatically.")
    import urllib.request
    payload = {
        "name": REPO,
        "private": (VISIBILITY == "private"),
        "has_issues": True,
        "has_projects": False,
        "has_wiki": False,
        "auto_init": False,
    }
    api = "https://api.github.com/user/repos"
    req = urllib.request.Request(
        api,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Authorization": f"Bearer {TOKEN}",
                 "Accept":"application/vnd.github+json",
                 "X-GitHub-Api-Version":"2022-11-28"}
    )
    with urllib.request.urlopen(req) as resp:
        if resp.status not in (200,201):
            raise SystemExit(f"GitHub API create repo failed: HTTP {resp.status}")
    print("→ Repo created via API")

def ensure_remote():
    remotes = git("remote", "-v", capture=True)
    if "origin" not in remotes:
        print(f"→ Adding remote origin {REMOTE_URL}")
        git("remote", "add", "origin", REMOTE_URL)
    else:
        print("→ Remote origin already set")

def commit_and_push():
    print("→ Adding files")
    git("add", "-A")
    has_commit = True
    try:
        git("rev-parse", "HEAD", capture=True)
    except subprocess.CalledProcessError:
        has_commit = False
    if has_commit:
        print(f"→ Committing: {MSG}")
        git("commit", "-m", MSG, check=False)
    else:
        print(f"→ First commit: {MSG}")
        git("commit", "-m", MSG)
    print("→ Pushing to GitHub")
    if PUSH_FORCE:
        git("push", "-u", "origin", BRANCH, "--force-with-lease")
    else:
        git("push", "-u", "origin", BRANCH)

def main():
    print("=== Supersonic GitHub Deploy ===")
    if OWNER == "your-username-or-org":
        print("! Set GITHUB_OWNER to your username/org.")
        sys.exit(1)
    ensure_git_repo()
    ensure_gitignore()
    ensure_lfs()
    ensure_workflow()
    create_repo_if_needed()
    ensure_remote()
    commit_and_push()
    print("\\n✅ Done.")
    print(f"Repo: https://github.com/{OWNER}/{REPO}")
    print(f"Branch: {BRANCH}")
    print("\\nTips:")
    print(" - To change visibility: VISIBILITY=public (or private)")
    print(" - To skip LFS: ADD_LFS=0")
    print(" - To skip CI workflow: ADD_WORKFLOW=0")
    print(" - To force update: PUSH_FORCE=1")

if __name__ == "__main__":
    main()
"""

# ---------------- replit_to_github.sh ----------------
REPLIT_TO_GH = r"""#!/usr/bin/env bash
set -euo pipefail

: "${GITHUB_OWNER:?Set GITHUB_OWNER to your GitHub username/org}"
: "${GITHUB_REPO:=SonicBuilder}"
: "${GIT_AUTHOR_NAME:=Christopher Elgin}"
: "${GIT_AUTHOR_EMAIL:=you@example.com}"
: "${VISIBILITY:=private}"
: "${ADD_LFS:=1}"
: "${ADD_WORKFLOW:=1}"
: "${PUSH_FORCE:=0}"

mkdir -p tools static/vendor/pdfjs static/vendor/jszip
if [[ ! -x tools/get_pdfjs.sh ]]; then
  cat > tools/get_pdfjs.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail
VER="4.6.82"
DEST="static/vendor/pdfjs"
mkdir -p "$DEST"
curl -sSL "https://unpkg.com/pdfjs-dist@${VER}/build/pdf.min.js"        -o "$DEST/pdf.min.js"
curl -sSL "https://unpkg.com/pdfjs-dist@${VER}/build/pdf.worker.min.js" -o "$DEST/pdf.worker.min.js"
echo "PDF.js ${VER} vendored into ${DEST}/"
SH
  chmod +x tools/get_pdfjs.sh
fi

if [[ ! -x tools/get_jszip.sh ]]; then
  cat > tools/get_jszip.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail
VER="3.10.1"
DEST="static/vendor/jszip"
mkdir -p "$DEST"
curl -sSL "https://unpkg.com/jszip@${VER}/dist/jszip.min.js" -o "$DEST/jszip.min.js"
echo "JSZip ${VER} vendored into ${DEST}/"
SH
  chmod +x tools/get_jszip.sh
fi

./tools/get_pdfjs.sh
./tools/get_jszip.sh

python3 deploy_github.py
"""

# ---------------- Makefile ----------------
MAKEFILE = r"""# SonicBuilder shortcuts
.PHONY: vendor run test push clean

vendor:
	@chmod +x tools/get_pdfjs.sh tools/get_jszip.sh || true
	@./tools/get_pdfjs.sh
	@./tools/get_jszip.sh

run:
	@FLASK_ENV=development CATALOG_TTL_HOURS=0.17 flask run

test:
	@python - <<'PY'
try:
	import app
	print("✅ app.py import OK")
except Exception as e:
	print("❌ app.py import failed:", e); raise
PY

push:
	@python3 deploy_github.py

clean:
	@rm -rf dist build .cache tmp || true
"""

# ---------------- CI Workflow ----------------
CI_YML = r"""name: Supersonic CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Vendor frontend libs (PDF.js / JSZip)
        run: |
          chmod +x tools/get_pdfjs.sh tools/get_jszip.sh
          ./tools/get_pdfjs.sh
          ./tools/get_jszip.sh

      - name: Smoke test import
        run: |
          python - <<'PY'
          try:
            import app
            print("✅ app.py import OK")
          except Exception as e:
            print("❌ app.py import failed:", e)
            raise
          PY

      - name: Upload vendored assets
        uses: actions/upload-artifact@v4
        with:
          name: static-vendor
          path: |
            static/vendor/pdfjs/*
            static/vendor/jszip/*

      - name: Upload docs (PDFs if any)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdfs
          path: |
            docs/**/*.pdf
          if-no-files-found: ignore
"""

# ---------------- Release Workflow ----------------
RELEASE_YML = r"""name: Supersonic Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare vendor libs
        run: |
          chmod +x tools/get_pdfjs.sh tools/get_jszip.sh || true
          ./tools/get_pdfjs.sh || true
          ./tools/get_jszip.sh || true

      - name: Build release zip
        run: |
          mkdir -p dist
          zip -r dist/SonicBuilder_${{ github.ref_name }}.zip . \
            -x "*.git*" ".github/*" "dist/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: SonicBuilder ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/SonicBuilder_${{ github.ref_name }}.zip
"""

# ---------------- Vendor Fetchers ----------------
GET_PDFJS = r"""#!/usr/bin/env bash
set -euo pipefail
VER="4.6.82"
DEST="static/vendor/pdfjs"
mkdir -p "$DEST"
curl -sSL "https://unpkg.com/pdfjs-dist@${VER}/build/pdf.min.js"        -o "$DEST/pdf.min.js"
curl -sSL "https://unpkg.com/pdfjs-dist@${VER}/build/pdf.worker.min.js" -o "$DEST/pdf.worker.min.js"
echo "PDF.js ${VER} vendored into ${DEST}/"
"""

GET_JSZIP = r"""#!/usr/bin/env bash
set -euo pipefail
VER="3.10.1"
DEST="static/vendor/jszip"
mkdir -p "$DEST"
curl -sSL "https://unpkg.com/jszip@${VER}/dist/jszip.min.js" -o "$DEST/jszip.min.js"
echo "JSZip ${VER} vendored into ${DEST}/"
"""

# ---------------- .env.example ----------------
ENV_EXAMPLE = r"""# Flask
FLASK_ENV=production
CATALOG_TTL_HOURS=24

# App-specific
# DIAGRAM_INDEX=./data/diagrams_index.json
"""

def main():
    write(ROOT / "deploy_github.py", DEPLOY_GITHUB, make_exe=False)
    write(ROOT / "replit_to_github.sh", REPLIT_TO_GH, make_exe=True)
    write(ROOT / "Makefile", MAKEFILE, make_exe=False)

    write(ROOT / ".github" / "workflows" / "supersonic-build.yml", CI_YML, make_exe=False)
    write(ROOT / ".github" / "workflows" / "supersonic-release.yml", RELEASE_YML, make_exe=False)

    write(ROOT / "tools" / "get_pdfjs.sh", GET_PDFJS, make_exe=True)
    write(ROOT / "tools" / "get_jszip.sh", GET_JSZIP, make_exe=True)

    write(ROOT / ".env.example", ENV_EXAMPLE, make_exe=False)

    print("\n✅ Bootstrap complete.")
    print("Next:")
    print("  chmod +x replit_to_github.sh")
    print('  export GITHUB_OWNER="YOUR_USER_OR_ORG"')
    print('  export GITHUB_REPO="SonicBuilder"')
    print('  export GIT_AUTHOR_NAME="Christopher Elgin"')
    print('  export GIT_AUTHOR_EMAIL="you@example.com"')
    print("  # (optional) gh auth login")
    print("  ./replit_to_github.sh")

if __name__ == "__main__":
    main()