name: Supersonic Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare vendor libs
        run: |
          chmod +x tools/get_pdfjs.sh tools/get_jszip.sh || true
          ./tools/get_pdfjs.sh || true
          ./tools/get_jszip.sh || true

      - name: Build release zip
        run: |
          mkdir -p dist
          zip -r dist/SonicBuilder_${{ github.ref_name }}.zip . \
            -x "*.git*" ".github/*" "dist/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: SonicBuilder ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/SonicBuilder_${{ github.ref_name }}.zip