#!/usr/bin/env python3
# release_notes_bootstrap.py — Enable auto release notes (draft + tagged)
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent

DRAFTER_CFG = """# .github/release-drafter.yml
name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement"]
  - title: "🐛 Fixes"
    labels: ["bug", "fix"]
  - title: "🧰 Maintenance"
    labels: ["chore", "deps", "refactor", "ci"]
  - title: "🧪 Tests"
    labels: ["test", "tests"]
  - title: "📚 Docs"
    labels: ["docs", "documentation"]
exclude-labels:
  - "skip-changelog"
template: |
  ## Highlights
  <!-- Add a quick summary here if you want -->

  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
  \n
  _Auto-generated by Release Drafter._"""

DRAFTER_WF = """# .github/workflows/release-notes.yml
name: Release Notes (Draft)
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, edited, closed, reopened, labeled, unlabeled, synchronize]
permissions:
  contents: write
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update draft notes
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
"""

def write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"→ wrote {path}")

def patch_release_workflow():
    # Tweak your existing supersonic-release.yml to add generate_release_notes: true
    wf = ROOT / ".github" / "workflows" / "supersonic-release.yml"
    if not wf.exists():
        print("! supersonic-release.yml not found — skipping patch (no problem).")
        return
    content = wf.read_text(encoding="utf-8")
    if "softprops/action-gh-release" not in content:
        print("! softprops/action-gh-release not detected — leaving file unchanged.")
        return
    if "generate_release_notes:" in content:
        print("→ release workflow already has generate_release_notes — no change.")
        return
    # Insert under 'with:' block for softprops step
    patched = re.sub(
        r"(uses:\s*softprops/action-gh-release@v2\s*\n\s*with:\s*\n)",
        r"\1          generate_release_notes: true\n",
        content,
        count=1,
        flags=re.IGNORECASE
    )
    if patched != content:
        wf.write_text(patched, encoding="utf-8")
        print("→ patched supersonic-release.yml with generate_release_notes: true")
    else:
        print("! Could not patch supersonic-release.yml automatically (please add manually under 'with:').")

def main():
    write(ROOT / ".github" / "release-drafter.yml", DRAFTER_CFG)
    write(ROOT / ".github" / "workflows" / "release-notes.yml", DRAFTER_WF)
    patch_release_workflow()
    print("\n✅ Auto Release Notes enabled.")
    print("Next:")
    print("  git add -A && git commit -m \"chore: enable auto release notes\" && git push origin main")
    print("Then:")
    print("  - Merge PRs with labels (feature/bug/docs/chore/test) to categorize entries.")
    print("  - Check the rolling draft under GitHub → Releases → 'Draft'.")
    print("  - When ready, tag a release (e.g., v1.0.0); notes will auto-fill.")

if __name__ == "__main__":
    main()