---
name: "🐞 Bug report"
about: Report a bug or unexpected behavior in the SonicBuilder toolchain.
title: "[BUG] "
labels: ["bug"]
assignees: []
---

## Description
<!-- Clearly describe the issue -->

## Steps to Reproduce
1. 
2. 
3. 

## Expected Behavior
<!-- What you expected to happen -->

## Actual Behavior
<!-- What actually happened -->

## Environment
- OS:
- Python version:
- SonicBuilder version/branch:
- Build mode (theme + annotation mode):

## Additional context
<!-- Screenshots, error logs, PDFs etc. -->
