name: SonicBuilder Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Build all bundles
        run: |
          python3 setup/package_all.py
      
      - name: Generate checksums
        run: |
          python3 supersonic/publish_to_pages.py
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Supersonic_*.zip
            docs/SHA256.txt
            docs/SIGNATURE.asc
            verify.log
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload release metadata
        uses: actions/upload-artifact@v4
        with:
          name: release-metadata
          path: |
            docs/SHA256.txt
            docs/SIGNATURE.asc
            verify.log
