#!/usr/bin/env python3
"""
Creates AI-generated release notes using commit history and changelog data.
"""
import os, subprocess
from pathlib import Path

def get_commits():
    try:
        return subprocess.check_output(["git","log","-n","10","--pretty=%s"]).decode()
    except Exception:
        return ""

def compose_text(commits):
    return f"""# Release Notes (AI-Generated)
## Highlights
{commits}

---

### System
- Auto-generated by Supersonic Control Core Reasoner
"""

def main():
    commits = get_commits()
    text = compose_text(commits)
    Path("AI_RELEASE_NOTES.md").write_text(text)
    print("AI release notes created ✅ (AI_RELEASE_NOTES.md)")

if __name__ == "__main__":
    main()
