#!/usr/bin/env python3
"""
bootstrap_supersonic.py
Writes all support files for SonicBuilder:
- deploy_github.py  (one-and-done GitHub deployer)
- replit_to_github.sh (Replit → GitHub wrapper)
- Makefile (nice shortcuts)
- GitHub Actions (CI + Release)
- vendor fetchers: tools/get_pdfjs.sh, tools/get_jszip.sh
- .env.example

Usage:
  python3 bootstrap_supersonic.py
Then:
  chmod +x replit_to_github.sh
  # (optional) gh auth login
  export GITHUB_OWNER=YOUR_USER_OR_ORG
  export GITHUB_REPO=SonicBuilder
  export GIT_AUTHOR_NAME="Christopher Elgin"
  export GIT_AUTHOR_EMAIL="you@example.com"
  ./replit_to_github.sh
"""

import os, stat
from pathlib import Path

ROOT = Path(__file__).resolve().parent

FILES = {
    # ---------------- deployer ----------------
    "deploy_github.py": r"""#!/usr/bin/env python3
import json, os, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

OWNER   = os.getenv("GITHUB_OWNER",   "your-username-or-org")
REPO    = os.getenv("GITHUB_REPO",    "SonicBuilder")
TOKEN   = os.getenv("GITHUB_TOKEN",   "")
AUTHOR  = os.getenv("GIT_AUTHOR_NAME","Supersonic Bot")
EMAIL   = os.getenv("GIT_AUTHOR_EMAIL","bot@example.com")
BRANCH  = os.getenv("GIT_DEFAULT_BRANCH","main")
MSG     = os.getenv("COMMIT_MSG","Supersonic: initial import")
PUSH_FORCE   = os.getenv("PUSH_FORCE","0") == "1"
ADD_LFS      = os.getenv("ADD_LFS","1") == "1"
ADD_WORKFLOW = os.getenv("ADD_WORKFLOW","1") == "1"
VISIBILITY   = os.getenv("VISIBILITY","private").lower().strip()

REMOTE_URL = f"https://github.com/{OWNER}/{REPO}.git"

LFS_PATTERNS = [
    "*.zip","*.7z","*.rar",
    "assets/audio/*.wav","assets/audio/*.mp3",
    "static/vendor/**",
    "docs/**/*.pdf","assets/**/*.pdf",
    "*.png","*.jpg","*.jpeg",
]

GITIGNORE = """__pycache__/
*.pyc
.env
.env.*
.venv/
venv/
dist/
build/
node_modules/
*.log
.DS_Store
.replit
replit.nix
.idea/
.vscode/
.cache/
*.cache/
pip-wheel-metadata/
*.zip
*.7z
*.tar
*.tar.gz
*.egg-info/
tmp/
local/
"""

WORKFLOW_YML = """name: Supersonic CI
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install basics
        run: |
          python -m pip install --upgrade pip
          pip install flask
      - name: Smoke test app import
        run: |
          python - <<'PY'
          try:
              import app
              print("✅ app.py import OK")
          except Exception as e:
              print("❌ app.py import failed:", e)
              raise
          PY
"""

def run(cmd, check=True, capture=False):
    if capture:
        return subprocess.run(cmd, check=check, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True).stdout